# Generated by Django 3.0 on 2021-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_category', models.CharField(max_length=20)),
                ('Product_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=128)),
                ('Customer_name', models.CharField(max_length=128)),
                ('Development_unit', models.CharField(max_length=128)),
                ('Customer_manager', models.CharField(max_length=50)),
                ('Opening_status', models.CharField(max_length=50)),
                ('Order_time', models.DateField()),
                ('Completion_time', models.DateField(null=True)),
                ('Quantity_ordered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='upload/%Y/%m/%d')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=20)),
                ('Monitor_points', models.CharField(max_length=128)),
                ('Longitude', models.DecimalField(decimal_places=12, max_digits=15)),
                ('Latitude', models.DecimalField(decimal_places=12, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=50)),
                ('pic_size', models.CharField(max_length=50, null=True)),
                ('pic_path', models.ImageField(default='pic_folder/None/no_image.pig', upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
