# Generated by Django 3.0 on 2020-07-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_category', models.CharField(max_length=20)),
                ('Product_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=128)),
                ('Customer_name', models.CharField(max_length=128)),
                ('Development_unit', models.CharField(max_length=128)),
                ('Customer_manager', models.CharField(max_length=50)),
                ('Opening_status', models.CharField(max_length=50)),
                ('Order_time', models.DateField()),
                ('Completion_time', models.DateField()),
                ('Quantity_ordered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='upload/%Y/%m/%d')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
