# Generated by Django 3.0 on 2020-07-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Completion_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='Order_time',
            field=models.CharField(max_length=50),
        ),
    ]
