# Generated by Django 3.0 on 2020-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0002_auto_20200719_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Completion_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='Order_time',
            field=models.DateField(),
        ),
    ]
