# Generated by Django 3.0 on 2020-07-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0003_auto_20200720_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Completion_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='Order_time',
            field=models.CharField(max_length=50),
        ),
    ]
