# Generated by Django 3.0 on 2020-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0004_auto_20200720_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Completion_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='Order_time',
            field=models.DateField(),
        ),
    ]
