# Generated by Django 3.0 on 2020-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0005_auto_20200720_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Completion_time',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='Order_time',
            field=models.FloatField(),
        ),
    ]
