# Generated by Django 3.0 on 2020-12-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0005_auto_20200720_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=20)),
                ('Monitor_points', models.CharField(max_length=128)),
                ('Longitude', models.DecimalField(decimal_places=12, max_digits=15)),
                ('Latitude', models.DecimalField(decimal_places=12, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=50)),
                ('pic_size', models.CharField(max_length=50, null=True)),
                ('pic_path', models.ImageField(default='pic_folder/None/no_image.pig', upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='Completion_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
