# Generated by Django 3.0 on 2020-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0006_auto_20200720_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Completion_time',
            field=models.FloatField(null=True),
        ),
    ]
