# Generated by Django 3.0 on 2020-12-21 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0006_auto_20201221_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
