# Generated by Django 3.0 on 2020-12-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0007_delete_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=50)),
                ('pic_size', models.CharField(max_length=50, null=True)),
                ('pic_path', models.ImageField(default='pic_folder/None/no_image.pig', upload_to='pic_folder/')),
            ],
        ),
    ]
