# Generated by Django 3.0 on 2020-07-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0007_auto_20200720_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Completion_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='Order_time',
            field=models.DateField(),
        ),
    ]
