# Generated by Django 3.0 on 2020-09-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
