# Generated by Django 3.0 on 2020-11-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0010_auto_20200916_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=20)),
                ('Monitor_points', models.CharField(max_length=128)),
                ('Longitude', models.DecimalField(decimal_places=12, max_digits=15)),
                ('Latitude', models.DecimalField(decimal_places=12, max_digits=15)),
            ],
        ),
    ]
